#mandatory
modLoader="javafml"
loaderVersion="[37,)"

#mandatory
license="LGPL-3.0"

#mandatory
[[mods]]
modId="thadv"
version="${file.jarVersion}"
displayName="NONAME"

#optional
authors="Techeart"
credits="NOCREDITS"
logoFile="logo.png"

#mandatory
description='''NODESCRIPTION'''

#optional
[[dependencies.thadv]]
modId="forge"
mandatory=true
versionRange="[37,)"
ordering="NONE"
side="BOTH"

[[dependencies.thadv]]
modId="minecraft"
mandatory=true
versionRange="[1.17.1,1.18)"
ordering="NONE"
side="BOTH"
